### ISSUE TITLE
这本书的原版在哪里？是不是考虑放到版本库中？

### ISSUE THREAD

**Issue by pylemon** [kitelife/The-AWK-Book-cn#1]
我想加入一起翻译

**Comment by kitelife** [comment]
哦，我网上找到一个清晰的电子版。感觉放在版本库里不是很好。如果你需要我发给你。欢迎加入翻译

**Comment by kitelife** [comment]
@pylemon 如果你要参加翻译的话，就fork+pull requests吧，近期我没什么时间翻译，忙着写论文毕业答辩。
